# Site Settings
title: My Resume
url: 'http://wytze.info'
baseurl: '/' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2 <-- blauwig, best prima
#style: styles-3 <-- groenig, niet zo mooi
#style: styles-4 <-- paars/rozig. ieuw
#style: styles-5 <-- geel, ieuw
style: styles-6

#Profile information
name: Wytze Vlietstra
tagline: Biosemantics & Semantic Web
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: | 
	testtest

#sidebar links
email: w.vlietstra@erasmusmc.nl
phone: +31-10-7044127
website: biosemantics.org #do not add http://
linkedin: wjvlietstra
github: Wytz
#twitter: '@webjeda'
#Update all the sections by editing the files inside _data folder.

# Tracker
#analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
