# Site Settings
title: My Resume
url: 'http://wytze.info'
baseurl: '/' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2 <-- blauwig, best prima
#style: styles-3 <-- groenig, niet zo mooi
#style: styles-4 <-- paars/rozig. ieuw
style: styles-5
#style: styles-6

#Profile information
name: Wytze Vlietstra
tagline: Biosemantics & Semantic Web
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: "I'm currently a researcher at the Erasmus University Medical Center, at the Medical Informatics department. My PhD focusses on using biomedical knowledge graphs to support data analyses and biomedical research in general. My promotor is Johan van der Lei, and my daily supervisors are Erik van Mulligen and Rein Vos (visiting professor from Maastricht University). Knowledge extracted from biomedical literature and datasets are semantically integrated with each other into a knowledge graph, after which this comprehensive body of biomedical knowledge is used for knowledge intensive tasks such as identifying migraine biomarkers to predicting the efficacy of drugs. The elements within these knowledge graphs consist of subject-predicate-object triples, along with the provenance of this triple. Triples also form the basic elements of the semantic web. However, while the semantic web adheres to specific standards (e.g. URI's), knowledge graphs do not necessarily adhere to these standards. For our research, [Euretos](http://www.euretos.com) has provided us access to their knowledge graph. Our most recent research efforts have led us to analyze the complex data extracted from knowledge graphs with machine learning. As future topics, I hope to investigate temporal aspects of knowledge graphs, as well as a detailed study into the provenance underlying triples. I have collaborated within both EU as well as national research projects, i.e. the EU FP7 Eureka project, and the NWO ODEX project."

#sidebar links
email: w.vlietstra@erasmusmc.nl
phone: +31-10-7044127
website: biosemantics.org #do not add http://
linkedin: wjvlietstra
github: Wytz
#twitter: '@webjeda'
#Update all the sections by editing the files inside _data folder.

# Tracker
#analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
